[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
address = "127.0.0.1"

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false

